/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Programa;

import sql.CrusSql;

/**
 *
 * @author YASMIN
 */
public class dieta extends javax.swing.JFrame {

    /**
     * Creates new form dieta
     */
    public dieta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSalir = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        MenuPrincipal1 = new javax.swing.JLabel();
        btnGenerarFactura1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt2 = new javax.swing.JComboBox<>();
        txt3 = new javax.swing.JComboBox<>();
        txt22 = new javax.swing.JComboBox<>();
        txt4 = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSalir.setBackground(new java.awt.Color(255, 102, 102));
        btnSalir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/png-clipart-button-shut-s-text-trademark.png"))); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 320, 50, 40));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Cena");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 50, 20));

        MenuPrincipal1.setFont(new java.awt.Font("Blackadder ITC", 0, 80)); // NOI18N
        MenuPrincipal1.setForeground(new java.awt.Color(153, 255, 102));
        MenuPrincipal1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MenuPrincipal1.setText("Crear dieta");
        getContentPane().add(MenuPrincipal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 340, 80));

        btnGenerarFactura1.setBackground(new java.awt.Color(153, 255, 153));
        btnGenerarFactura1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGenerarFactura1.setText("GUARDAR");
        btnGenerarFactura1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarFactura1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenerarFactura1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 330, 150, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Desayuno");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 120, 20));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setText("Merienda");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 120, 20));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Almuerzo");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 100, 20));

        txt2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cereales con leche", "Yogurt", "Cafe", "Te", "Enbutidos con leche , cafe o te", "Tostadas con leche , cafe o te" }));
        getContentPane().add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, -1, -1));

        txt3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pasta con yogurt, te o cafe", "Pasta con polloSalmón con puré de papas", "Brochetas de pollo con verduras ", "Pollo a la plancha con arroz chaufa", "Atún con ensalada de verduras y lechuga ", "Lomo de cerdo con arroz ", "Trucha al horno con yuca" }));
        getContentPane().add(txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, -1, -1));

        txt22.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Almendra con fresas ", "Yogurt y una fruta ", "Ensalada de fruta ", "Gelatina ", "Manzana con yogurt ", "Jugo hervido con fruta ", "Yogurt descremado" }));
        getContentPane().add(txt22, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, -1));

        txt4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tortillas de zanahoria", "Quinua cocida", "Sopa de crema ", "Carne con ensalada de espinaca ", "Pizza con verduras ", "Sopa de verduras ", "Pescado a la plancha con ensalada cruda" }));
        getContentPane().add(txt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, 20));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/resp/crop1.jpg"))); // NOI18N
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 550, 380));
        getContentPane().add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 250, 120, 30));
        getContentPane().add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 120, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents
CrusSql objcrud = new CrusSql();
    private void btnGenerarFactura1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarFactura1ActionPerformed
        objcrud.insertadiet( txt2.getItemAt(txt2.getSelectedIndex()), txt22.getItemAt(txt22.getSelectedIndex()), txt3.getItemAt(txt3.getSelectedIndex()), txt4.getItemAt(txt4.getSelectedIndex()));
    }//GEN-LAST:event_btnGenerarFactura1ActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        menuprin o = new menuprin();
        o.setVisible(true);
        o.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dieta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dieta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dieta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dieta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new dieta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MenuPrincipal1;
    private javax.swing.JButton btnGenerarFactura1;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JComboBox<String> txt2;
    private javax.swing.JComboBox<String> txt22;
    private javax.swing.JComboBox<String> txt3;
    private javax.swing.JComboBox<String> txt4;
    // End of variables declaration//GEN-END:variables
}
