/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Programa;

import sql.CrusSql;

/**
 *
 * @author YASMIN
 */
public class RUTINA extends javax.swing.JFrame {

    /**
     * Creates new form RUTINA
     */
    public RUTINA() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnGenerarFactura = new javax.swing.JButton();
        btnSalir1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt1 = new javax.swing.JComboBox<>();
        txt2 = new javax.swing.JComboBox<>();
        txt3 = new javax.swing.JComboBox<>();
        txt4 = new javax.swing.JComboBox<>();
        S = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Blackadder ITC", 0, 80)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 255, 255));
        jLabel2.setText("Crear Rutina");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 410, 78));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 255, 255));
        jLabel3.setText("Tipo de rutina");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 100, -1));

        btnGenerarFactura.setBackground(new java.awt.Color(204, 204, 255));
        btnGenerarFactura.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnGenerarFactura.setText("GUARDAR");
        btnGenerarFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarFacturaActionPerformed(evt);
            }
        });
        getContentPane().add(btnGenerarFactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 170, 30));

        btnSalir1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/exit.png"))); // NOI18N
        btnSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, -1, 50));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 255, 255));
        jLabel7.setText("Tiempo de descanso");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 120, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 255, 255));
        jLabel9.setText("Tiempo de ejercicio");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 120, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 255, 255));
        jLabel11.setText("Ejercicios");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, 100, -1));

        txt1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Flexiones", "Abdominales", "Saltos doble comba", "Saltos simples de comba", "Sentadillas", "Remo", "Ciclismo", "Recuperacion consistente", " " }));
        getContentPane().add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, 40));

        txt2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 repeticion", "2 repeticiones", "3 repeticiones", "4 repeticiones", "8 repeticiones", "12 repeticiones", "20 repeticiones", "30 repeticiones" }));
        getContentPane().add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, -1, -1));

        txt3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 - 2 minutos", "2 - 5 minutos", "5 - 8 minutos", "8 - 12 minutos", "12 -20 minutos", "20 - 30 minutos " }));
        getContentPane().add(txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, -1, -1));

        txt4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1 - 3  minutos", "3 - 6  minutos", "6 - 9 minutos", "9 - 12 minutos" }));
        getContentPane().add(txt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, -1, -1));

        S.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/resp/crop1.jpg"))); // NOI18N
        getContentPane().add(S, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents
CrusSql objcrud = new CrusSql();
    private void btnGenerarFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarFacturaActionPerformed
        objcrud.insertarrut(txt1.getItemAt(txt1.getSelectedIndex()), txt2.getItemAt(txt2.getSelectedIndex()), txt3.getItemAt(txt3.getSelectedIndex()), txt4.getItemAt(txt4.getSelectedIndex()));
    }//GEN-LAST:event_btnGenerarFacturaActionPerformed

    private void btnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir1ActionPerformed
       menuprin o = new menuprin();
            o.setVisible(true);
            o.setLocationRelativeTo(null);
            this.setVisible(false);
    }//GEN-LAST:event_btnSalir1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RUTINA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RUTINA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RUTINA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RUTINA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RUTINA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel S;
    private javax.swing.JButton btnGenerarFactura;
    private javax.swing.JButton btnSalir1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> txt1;
    private javax.swing.JComboBox<String> txt2;
    private javax.swing.JComboBox<String> txt3;
    private javax.swing.JComboBox<String> txt4;
    // End of variables declaration//GEN-END:variables
}
