/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import comunicacionserial.ArduinoExcepcion;
import comunicacionserial.ComunicacionSerial_Arduino;
import getset.variables;
import itp_library.imformacion;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import jssc.SerialPortEvent;
import jssc.SerialPortEventListener;
import jssc.SerialPortException;
import sql.CrusSql;

/**
 *
 * @author YASMIN
 */
public class deportista extends javax.swing.JFrame {

    ComunicacionSerial_Arduino conexion = new ComunicacionSerial_Arduino();
    SerialPortEventListener listen = new SerialPortEventListener() {
        @Override
        public void serialEvent(SerialPortEvent serialPortEvent) {

            try {
                if (conexion.isMessageAvailable()) {
                    txt1.setText(conexion.printMessage());
                    conexion.killArduinoConnection();
                }
            } catch (SerialPortException ex) {
                Logger.getLogger(deportista.class.getName()).log(Level.SEVERE, null, ex);
            } catch (ArduinoExcepcion ex) {
                Logger.getLogger(deportista.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    };

    public deportista() {
        initComponents();
        try {
            conexion.arduinoRXTX("COM11", 9600, listen);
        } catch (ArduinoExcepcion ex) {
            Logger.getLogger(deportista.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnConsultar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_datosMascota = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        panel1 = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        label5 = new java.awt.Label();
        label6 = new java.awt.Label();
        label7 = new java.awt.Label();
        btnGuardar = new javax.swing.JButton();
        label8 = new java.awt.Label();
        txt4 = new javax.swing.JTextField();
        cmbdep1 = new javax.swing.JComboBox<>();
        txt3 = new javax.swing.JTextField();
        txt7 = new javax.swing.JTextField();
        txt8 = new com.toedter.calendar.JDateChooser();
        txt5 = new com.toedter.calendar.JDateChooser();
        txt1 = new javax.swing.JTextField();
        txt2 = new javax.swing.JComboBox<>();
        cmbdep2 = new javax.swing.JComboBox<>();
        btnSalir = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(2, 75, 91));

        jLabel2.setBackground(new java.awt.Color(255, 255, 102));
        jLabel2.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CONSULTA DE DEPORTISTA");

        btnConsultar.setBackground(new java.awt.Color(0, 153, 153));
        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenSistem/1 consulta.png"))); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenSistem/1 consulta.png"))); // NOI18N
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        tbl_datosMascota.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        tbl_datosMascota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbl_datosMascota.setSelectionBackground(new java.awt.Color(204, 255, 204));
        jScrollPane1.setViewportView(tbl_datosMascota);

        jButton1.setText("Modificar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Eliminar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnConsultar, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jButton1)
                        .addGap(57, 57, 57)
                        .addComponent(jButton2))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 396, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConsultar)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 690, 300));

        panel1.setBackground(new java.awt.Color(2, 75, 91));
        panel1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        panel1.setForeground(new java.awt.Color(255, 255, 255));
        panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(102, 0, 255));
        jLabel1.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REGISTRO DE DEPORTISTA");
        panel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, 367, 32));

        label1.setBackground(new java.awt.Color(0, 204, 204));
        label1.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label1.setText(" Código: ");
        panel1.add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 42, 67, 24));

        label2.setBackground(new java.awt.Color(0, 204, 204));
        label2.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label2.setText(" Genero:");
        panel1.add(label2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 67, -1));

        label3.setBackground(new java.awt.Color(0, 204, 204));
        label3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label3.setText(" Nombre : ");
        panel1.add(label3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 67, -1));

        label4.setBackground(new java.awt.Color(0, 204, 204));
        label4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label4.setText(" Direccion: ");
        panel1.add(label4, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 149, -1, -1));

        label5.setBackground(new java.awt.Color(0, 204, 204));
        label5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label5.setText(" Fecha de Nacimiento:");
        panel1.add(label5, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 42, 129, -1));

        label6.setBackground(new java.awt.Color(0, 204, 204));
        label6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label6.setText(" Edad:");
        panel1.add(label6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, -1, -1));

        label7.setBackground(new java.awt.Color(0, 204, 204));
        label7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label7.setText(" Fecha Registro: ");
        panel1.add(label7, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 138, 129, -1));

        btnGuardar.setBackground(new java.awt.Color(0, 153, 153));
        btnGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenSistem/guardar.png"))); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenSistem/guardar.png"))); // NOI18N
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        panel1.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(578, 168, -1, -1));

        label8.setBackground(new java.awt.Color(0, 204, 204));
        label8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        label8.setText(" Deporte:");
        panel1.add(label8, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, -1, -1));
        panel1.add(txt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 180, -1));

        cmbdep1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmbdep1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Atletsimo", "Caminata", "Futbol", "Tenis", "Baloncesto", "Balonmano", "voley" }));
        panel1.add(cmbdep1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, -1, -1));
        panel1.add(txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 170, -1));
        panel1.add(txt7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 170, 20));
        panel1.add(txt8, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 140, -1, -1));
        panel1.add(txt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 40, -1, -1));
        panel1.add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 130, -1));

        txt2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txt2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Femenino" }));
        panel1.add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, -1, 20));

        cmbdep2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        cmbdep2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Atletsimo", "Caminata", "Futbol", "Tenis", "Baloncesto", "Balonmano", "voley" }));
        panel1.add(cmbdep2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, -1, -1));

        getContentPane().add(panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 690, 200));

        btnSalir.setBackground(new java.awt.Color(0, 153, 153));
        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenSistem/SALIR.png"))); // NOI18N
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 560, 30, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/resp/crop1.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 750, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    CrusSql objcrud = new CrusSql();
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        SimpleDateFormat sdf=new SimpleDateFormat("dd/MM/YYYY");
        objcrud.insertar(txt1.getText(), txt2.getItemAt(txt2.getSelectedIndex()), txt3.getText(), txt4.getText(), sdf.format(txt5.getCalendar().getTime()), sdf.format(txt8.getCalendar().getTime()), txt7.getText(), cmbdep1.getItemAt(cmbdep1.getSelectedIndex()));
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        objcrud.Mostrartb(tbl_datosMascota);
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:

        imformacion oc = new imformacion();
        oc.setVisible(true);
        oc.setLocationRelativeTo(null);
        this.setVisible(false);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         SimpleDateFormat sdf=new SimpleDateFormat("dd/MM/YYYY");
        objcrud.actualizardep(txt1.getText(), txt2.getItemAt(txt2.getSelectedIndex()), txt3.getText(), txt4.getText(), sdf.format(txt5.getCalendar().getTime()), sdf.format(txt8.getCalendar().getTime()), txt7.getText(), cmbdep1.getItemAt(cmbdep1.getSelectedIndex()));
 
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        objcrud.eliminardep(txt1.getText());
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(deportista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(deportista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(deportista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(deportista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new deportista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> cmbdep1;
    private javax.swing.JComboBox<String> cmbdep2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Panel panel1;
    private javax.swing.JTable tbl_datosMascota;
    private javax.swing.JTextField txt1;
    private javax.swing.JComboBox<String> txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt4;
    private com.toedter.calendar.JDateChooser txt5;
    private javax.swing.JTextField txt7;
    private com.toedter.calendar.JDateChooser txt8;
    // End of variables declaration//GEN-END:variables
}
