/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package itp_library;

/**
 *
 * @author YASMIN
 */
public class inf3 extends javax.swing.JPanel {

    /**
     * Creates new form inf3
     */
    public inf3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("condiciones Estas patologias interfieren con la capacidad de la persona para");
        content.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 550, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Son un grupo de afecciones de salud fisica en las cuales una persona presenta");
        content.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 670, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("cambios negativos en su cuerpo, un patrón prolongado de comportamientos,");
        content.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 530, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setText("escenarios.");
        content.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 670, 47));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("emociones y pensamientos que hacen que la persona no se encuentre en optimas");
        content.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, 550, 47));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setText("desempeñarse de manera eficaz en las actividades que realiza, el trabajo y otros");
        content.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 660, 47));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/itp_library/images/xray.png"))); // NOI18N
        content.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 40, -1, -1));

        add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 450));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
