/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package itp_library;

/**
 *
 * @author YASMIN
 */
public class inf6 extends javax.swing.JPanel {

    /**
     * Creates new form inf6
     */
    public inf6() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        content = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        content.setBackground(new java.awt.Color(255, 255, 255));
        content.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("-Su evaluación es muy importante y es característica de un examen físico general.");
        content.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 670, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setText("-Proporcionar información objetiva y básica sobre la vitalidad de una persona.");
        content.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 540, 30));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setText("-Puede indicar un estado morboso o peligroso en un individuo.");
        content.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 470, 47));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/itp_library/images/ODCCDSD.png"))); // NOI18N
        content.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, -1, -1));

        add(content, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 410));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel content;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables
}
