/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package paraestadistica.ii_proyecto;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class FormBinomial extends javax.swing.JFrame {

    /**
     * Creates new form CalculoEstadistica
     */
    DefaultTableModel modelo;
    public FormBinomial() {
        initComponents();
        modelo=new DefaultTableModel();
        modelo.addColumn("Resultado");
        
        tblResultado.setModel(modelo);
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtValorP = new javax.swing.JTextField();
        txtValorN = new javax.swing.JTextField();
        txtValork = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        etiRes = new javax.swing.JLabel();
        btnCalcular = new javax.swing.JButton();
        btnMenuInicio = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        etiResFinal = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResultado = new javax.swing.JTable();
        btnGuardar = new javax.swing.JButton();

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("%");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Ingrese Valor de p:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 93, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Ingrese el valor de n:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 139, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Ingrese el valor de k:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 187, -1, -1));

        txtValorP.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtValorP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorPActionPerformed(evt);
            }
        });
        getContentPane().add(txtValorP, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 90, 75, -1));

        txtValorN.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtValorN, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 136, 75, -1));

        txtValork.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        getContentPane().add(txtValork, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 184, 75, -1));

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/clean.jpg"))); // NOI18N
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(117, 318, 46, 51));

        etiRes.setBackground(new java.awt.Color(255, 255, 153));
        etiRes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etiRes.setForeground(new java.awt.Color(204, 0, 0));
        etiRes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(etiRes, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 228, 63, 30));

        btnCalcular.setText("CALCULAR");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        getContentPane().add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        btnMenuInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imf.jpg"))); // NOI18N
        btnMenuInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuInicioActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenuInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 318, 40, -1));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));

        jLabel4.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        jLabel4.setText("DISTRIBUCION BINOMIAL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(103, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(83, 83, 83))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(18, 18, 18))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("x100");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 233, -1, -1));

        etiResFinal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        etiResFinal.setForeground(new java.awt.Color(204, 0, 0));
        etiResFinal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(etiResFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 228, 60, 30));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("%");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 233, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("%");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 89, -1, -1));

        tblResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Resultado"
            }
        ));
        jScrollPane1.setViewportView(tblResultado);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 110, 169));

        btnGuardar.setText("GUARDAR");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 280, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        // TODO add your handling code here:
        txtValorP.setText(null);
        txtValorN.setText(null);
        txtValork.setText(null);
        etiRes.setText(null);
        etiResFinal.setText(null);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    
    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        DecimalFormat df=new DecimalFormat("0.0000");
        DecimalFormat df2=new DecimalFormat("0.00");
        
        String aux;
        int b,c,exp;
        double a,d,q,p,resultado,resFinal;
        aux=txtValorP.getText();
        a=Integer.parseInt(aux);//convierte aux que es tipo String a entero o int y asigna a la variable a
        p=a/100;
        aux=txtValorN.getText();
        b=Integer.parseInt(aux);
        aux=txtValork.getText();
        c=Integer.parseInt(aux);
        q=1-p;
        d=a+b+c;
        exp=b-c;
        double rf=(potencia(p, c));
        double et=(potencia(q, exp));
        int comb=((factorialRecursivo(b))/((factorialRecursivo(exp))*(factorialRecursivo(c))));
        resultado=(comb*rf*et);
        
        etiRes.setText(df.format(resultado));
        etiResFinal.setText(df2.format(resultado*100));
    }//GEN-LAST:event_btnCalcularActionPerformed

    public static int factorialRecursivo(int numero){
         int res;
         if(numero==1){
            //Se termina la recursión
            return 1;
        }
else{

      //Se llama asi misma la funcion, con el valor del numero menos 1
           
res = numero * factorialRecursivo(numero-1);
        
}
       //Devolvemos el valor
        
return res;
      }
    
    public static double potencia(double base, int exponente) {
         if (exponente == 0) { //caso base
            return 1; //10^0 = 1
        } else if (exponente == 1) { //caso base
            return base; //10^1 = 10
        } else if (exponente < 0) { //Exponente negativo
            return potencia(base, exponente + 1) / base;

        } else 
{  //Exponente positivo
            return base * potencia(base, exponente - 1);
        }
     }
    
    private void txtValorPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorPActionPerformed

    private void btnMenuInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuInicioActionPerformed
        // TODO add your handling code here:
        FormInicio fi=new FormInicio();
        
        fi.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMenuInicioActionPerformed

   
    
    void llevaVectorATabla(int T[],int N)
    {
        DefaultTableModel dtm2=new DefaultTableModel();
      for(int i=0;i<N; i++)
        {
           T[i]=(int)tblResultado.getValueAt(i, 0);
        }
    }
    
    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:50
        String v1=etiResFinal.getText();
        String d="%";
        String numeros[]={v1};
        modelo.addRow(numeros);
        
    }//GEN-LAST:event_btnGuardarActionPerformed

    /*void llenarVector(int v[],int N)
    {
       String aux;
       dtm=(DefaultTableModel)tblResultado.getModel();
       dtm.setRowCount(N);
       dtm.setColumnCount(1);
       
       for(int i=0;i<N; i++)
       {
           aux=etiRes.getText();
           v[i]=Integer.parseInt(aux);
           tblResultado.setValueAt(v[i], i, 0);
       }
    }*/
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormBinomial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormBinomial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormBinomial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormBinomial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormBinomial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnMenuInicio;
    private javax.swing.JLabel etiRes;
    private javax.swing.JLabel etiResFinal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblResultado;
    private javax.swing.JTextField txtValorN;
    private javax.swing.JTextField txtValorP;
    private javax.swing.JTextField txtValork;
    // End of variables declaration//GEN-END:variables
}
